import { Typography } from "@originprotocol/origin-storybook";
import React from "react";
import { Gradient2Button } from "../../components";

interface Step2Props {
  stakingApy: number;
  className?: string;
}

const Step2 = ({ stakingApy, className }: Step2Props) => {
  return (
    <div className={className}>
      <Typography.Body2 className="font-medium text-blurry">
        With your OGV in a Web3 wallet (e.g. Metamask), connect to
        <span className="ml-1 text-[#ffcf88]">
          the OUSD governance staking page.
        </span>
      </Typography.Body2>

      <Typography.Body2 className="font-normal mt-4 text-white-grey">
        Select the amount of OGV you wish to stake and your desired duration. A
        longer lock-up will maximize your voting power and your share of the
        variable staking rewards.
      </Typography.Body2>

      <Gradient2Button
        outerDivClassName="mt-10"
        className="bg-transparent hover:bg-transparent py-3 px-8 lg:px-10"
        onClick={() =>
          process.browser &&
          window.open(
            "https://governance.ousd.com/stake",
            "_blank",
            "noopener noreferrer"
          )
        }
      >
        <Typography.Body2>Stake OGV</Typography.Body2>
      </Gradient2Button>

      <div className="bg-gradient-to-r from-gradient1-fromt to-gradient1-tot mt-10 p-6 lg:p-10 rounded-lg">
        <Typography.H6 className="text-gradient1">
          Earn {stakingApy.toFixed(2)}% APY
        </Typography.H6>
        <Typography.Body3 className="text-blurry leading-[23px] mt-3 text-sm font-medium">
          OGV stakers earn fees generated by OUSD and OETH.
        </Typography.Body3>
      </div>
    </div>
  );
};

export default Step2;
