@startuml

title "Origin Ether Contract Dependencies"

object "OETHZapper" as zap <<Origin>> #DeepSkyBlue {
}

object "OETHDripper" as drip <<Origin>><<Proxy>> #DeepSkyBlue {
}


object "WOETH" as woeth <<Origin>><<Proxy>> #DeepSkyBlue {
    asset: OETH
    symbol: WOETH
    name: Wrapped OETH
}

object "OETH" as oeth <<Origin>><<Proxy>> #DeepSkyBlue {
    symbol: OETH
    name: Origin Ether
}

object "OETHVaultCore" as oethv <<Origin>><<Proxy>> #DeepSkyBlue {
}

object "OETHHarvester" as harv <<Origin>><<Proxy>> #DeepSkyBlue {
}

' Oracle
object "OETHOracleRouter" as oracle <<Origin>> #DeepSkyBlue {
}
object "EACAggregatorProxy" as chain <<Chainlink>> {
    prices: CVX/ETH, CRV/ETH,\nrETH/ETH, stETH/ETH, frxETH/ETH,\nWETH/ETH 
}

' SushiSwap
object "UniswapV2Router02" as sushi <<SushiSwap>> {
    pairs: CRV/ETH, CVX/ETH
}

' Strategies

object "Generalized4626Strategy" as frxethstrat <<Origin>><<Proxy>> #DeepSkyBlue {
}

object "sfrxETH" as sfrxeth <<FRAX>> {
    asset: frxETH
    symbol: sfrxETH
    name: Staked Frax Ether
}

' Curve
object "ConvexEthMetaStrategy" as cvxStat <<Origin>><<Proxy>> #DeepSkyBlue {
}
object "Gauge" as gauge <<Curve>> {
    asset: OETHCRV-f
    symbol: OETHCRV-f-gauge
    name: Curve.fi OETHCRV-f Gauge Deposit
}
object "StableSwap" as crvPool <<Curve>> {
    assets: [ETH, OETH]
    symbol: OETHCRV-f
    name: Curve.fi Factory Pool: OETH
}
' Convex
' object "Booster" as cvxBoost <<Convex>> {
' }
object "BaseRewardPool" as cvxPool <<Convex>> {
}
object "DepositToken" as cvxPoolLp <<Convex>> {
    symbol: cvxOUSD3CRV-f
    name: Origin Dollar Convex Deposit
}

' Assets
object "frxETH" as frxeth <<FRAX>> {
    symbol: frxETH
    name: Frax Ether
}

object "WETH9" as weth <<Dapphub>> {
    symbol: WETH
    name: Wrapped Ether
}

object "RocketTokenRETH" as reth <<Rocket Pool>> {
    symbol: rETH
    name: Rocket Pool ETH
}

object "Lido" as steth <<Lido>><<Proxy>> {
    symbol: stETH
    name: Liquid staked Ether 2.0
}

' Rewards 
object "ConvexToken" as cvx <<Convex>> {
    symbol: CVX
    name: Convex Token
}

object "Curve DAO Token" as crv <<Convex>> {
    symbol: CRV
    name: Curve DAO Token
}

zap ..> oeth
zap ..> oethv
zap ....> sfrxeth
zap .....> frxeth
zap .....> weth

drip ...> weth
oethv <.. drip

harv .> oethv
harv ...> sushi
harv ....> cvx
harv ....> crv

woeth ..> oeth
oeth <.> oethv
oethv ..> oracle
oracle ..> chain

' Staked FRAX ETH Strategy
oethv ..> frxethstrat
frxethstrat ..> sfrxeth

' Convex ETH Metapool Strategy
harv <..> cvxStat
oethv <..> cvxStat
oeth <.. cvxStat
' cvxStat ..> cvxBoost
' cvxBoost .[hidden]> cvxPool
cvxStat ..> crvPool
cvxStat ..> cvxPool
cvxStat ...> weth
cvxStat ...> cvx
cvxStat ...> crv
cvxPool ..> cvxPoolLp
cvxPool ..> crv
cvxPool .> gauge
gauge .> crvPool
oeth <... crvPool

' Vault to Assets
oethv ....> frxeth
oethv ....> weth
oethv ....> reth
oethv ....> steth

sfrxeth ..> frxeth

@enduml
