@startuml

title "OETH Flow of Value"

actor "User" as user
actor "Anyone" as anyone
actor "Trustee" as trust <<Origin>> #DeepSkyBlue
participant "Zapper" as zap <<Origin>> #DeepSkyBlue
participant "OETH\nVault" as vault <<Origin>> #DeepSkyBlue
participant "Harvester" as harv <<Origin>> #DeepSkyBlue
participant "Dripper" as drip <<Origin>> #DeepSkyBlue
participant "Swapper" as swapper <<Origin>> #DeepSkyBlue
participant "OGV\nRewards" as ogvRewards <<Origin>> #DeepSkyBlue
participant "Buyback" as buyBack <<Origin>> #DeepSkyBlue

participant "FRAX\nStrategy" as frxStrat <<Origin>> #DeepSkyBlue
participant "FRAX ETH" as frxETH <<FRAX>><<frxETH>>
participant "Staked\nFRAX ETH" as sfrxETH <<FRAX>><<sfrxETH>>

participant "Curve AMO\nStrategy" as crvStrat <<Origin>> #DeepSkyBlue
participant "OETH-ETH\nPool" as oethCrv <<Curve>>
participant "OETH-ETH\nPool" as oethCvx <<Convex>>
participant "Rewards\nPool" as cvxRewards <<Convex>>
participant "Locked\nCVX" as icvx <<Convex>>

participant "rETH/WETH\nBalancer\nMetaStable\nStrategy" as balMetaStrat <<Origin>> #DeepSkyBlue
participant "Balancer\nVault" as balVault <<Balancer>>
participant "rETH\nMetaStable\nPool" as balMetaPool <<Balancer>>
participant "rETH\nRewards\nPool" as auraRewards <<Aura>>

participant "frxETH/WETH\nConvex\nStrategy" as cvxFrxStrat <<Origin>> #DeepSkyBlue
participant "frxETH-WETH\nPool" as frxCrv <<Curve>>
participant "frxETH-WETH\nStaked Convex" as frxCvStk <<Frax>>
participant "frxETH-WETH\nLocked Stake" as frxCvStkLck <<Frax>>
participant "frxETH-WETH\nPool" as frxCvx <<Convex>>
participant "frxETH-WETH\nRewards" as cvxFrxRewards <<Convex>>

participant "Morpho Aave\nStrategy" as morphAaveStrat <<Origin>> #DeepSkyBlue
participant "Morpho\nAave V2" as morpho <<Morpho>>
participant "interst\nbearing\nWETH" as aweth <<Aave>><<aWETH>>
participant "variable\ndebt WETH" as vdweth <<Aave>><<varDebtWETH>>

participant "TriCrv\ncrvUSD/ETH/CRV" as triCrv <<Curve>>
participant "cvxeth\nCVX/ETH" as cvxeth <<Curve>>
participant "FXS/ETH\nV3 Pool" as uniFxs <<Uniswap>>
participant "Universal\nRouter" as uniRouter <<Uniswap>>
participant "OETH/ETH\nV3 Pool" as uniOeth <<Uniswap>>
participant "OGV/ETH\nV3 Pool" as uniOgv <<Uniswap>>
participant "CVX/ETH\nV3 Pool" as uniCvx <<Uniswap>>

participant "Wrapped ETH" as weth <<DappHub>><<WETH>>

participant "1Inch\nRouter" as 1r <<1Inch>>

' Deposit ETH via Zapper
group User deposit ETH [> 10 OETH]
user -> zap : ETH
note left : ETH in user tx

zap -> weth : ETH
note left : swap ETH for WETH
weth o-> zap : WETH

vault o-> trust : OETH
note left : 20% performance\nfee from rebase

zap -> vault : WETH

note over vault : Currently no default WETH strategy\nso there is no auto allocation.

vault o-> user : OETH
note left : mint OETH\nto match ETH
end

' Deposit sfrxETH via Zapper
group User deposit sfrxETH [> 10 OETH]
note over zap : User approves Zapper to transfer their sfrxETH

user -x sfrxETH : sfrxETH
note left : redeem sfrxETH for frxETH
sfrxETH -> zap : frxETH

vault o-> trust : OETH
note left : 20% performance\nfee from rebase

zap -> vault : frxETH

group FRAX Strategy
vault -> frxStrat : frxETH
note left: > 10 ETH worth so allocate\nto default frxETH strategy
frxStrat -> sfrxETH : frxETH
note left : deposit frxETH
sfrxETH o-> frxStrat : sfrxETH
note left : get sfrxETH shares
end 

vault o-> user : OETH
note left : mint OETH to match\nETH value of frxETH
end


' Mint
group User mint [< 10 OETH]
vault o-> trust : OETH
note left : 20% performance\nfee from rebase

user -> vault : frxETH, stETH, rETH or WETH
note left: Only to vault,\nnot strategy as <10 ETH
vault o-> user : OETH
note left : mint OETH to\nETH value of deposit
end

' Allocate
group Vault allocate [anyone can call]

' FRAX Strategy for frxETH
group Deposit frxETH to FRAX Strategy [unallocated frxETH in vault]
vault -> frxStrat : frxETH
frxStrat -> sfrxETH : frxETH
note left : deposit frxETH
sfrxETH o-> frxStrat : sfrxETH
note left : get sfrxETH shares
end

' FRAX Strategy for WETH
group Deposit WETH to FRAX Strategy [unallocated WETH in vault]
vault -> frxStrat : WETH
frxStrat -x weth : WETH
note left : withdraw ETH from WETH
weth -> frxStrat : ETH
frxStrat -> frxETH : ETH
note left : Deposit and stake ETH for sfrxETH
frxETH -> sfrxETH : frxETH
sfrxETH o-> frxStrat : sfrxETH
end

' Curve AMO Strategy
group Deposit WETH to Curve AMO Strategy [unallocated WETH in vault]
vault -> crvStrat : WETH
note left : Vault transfers\nWETH to strategy
crvStrat -x weth : WETH
note left : WETH is burned
weth -> crvStrat : ETH
note left : ETH is withdrawn

vault o-> crvStrat : OETH
note left : Vault mints OETH
crvStrat -> oethCrv : ETH, OETH
note left : add liquidity to the Curve pool
oethCrv o-> crvStrat : OETHCRV-f
note left: strategy gets Curve pool LP tokens

crvStrat -> oethCvx : OETHCRV-f
note left : deposit Curve pool LP to Convex
oethCvx o-> cvxRewards : cvxOETHCRV-f
note left : stake Convex LP tokens
end

' Balancer MetaPool Strategy
group Deposit rETH and WETH to Balancer MetaStable Strategy [unallocated rETH and WETH in vault]
vault -> balMetaStrat : rETH and WETH
note left : Vault transfers\nrETH and WETH to strategy
balMetaStrat -> balVault : rETH and WETH
note left : join Balancer pool
balMetaPool o-> balMetaStrat : B-rETH-STABLE
balMetaStrat -> auraRewards : B-rETH-STABLE
note left : deposit BPT to Aura
auraRewards o-> balMetaStrat : auraB-rETH-STABLE-vault

end

' Frax Convex strategy for the Curve frxETH/WETH pool
group Deposit WETH or frxETH to Frax Convex Strategy using Curve frxETH/WETH pool [unallocated WETH or frxETH in vault]
vault -> cvxFrxStrat : WETH or frxETH
note left : Vault transfers\nasset to strategy
cvxFrxStrat -> frxCrv : WETH or frxETH
note left : add liquidity to the Curve pool
frxCrv o-> cvxFrxStrat : frxeth-ng-f
note left: strategy gets Curve pool LP tokens

cvxFrxStrat -> frxCvStk : frxeth-ng-f
note left : deposit to Frax Convex Staking
frxCvStk -> frxCvx : frxeth-ng-f
note left : deposit to Convex pool
frxCvx o-> cvxFrxRewards : cvxfrxeth-ng-f
note left : stake Convex LP tokens
frxCvStk o-> cvxFrxStrat : stkcvxfrxeth-ng-f-frax
note left : mint Staked Frax Convex LP tokens

end

' Morpho Aave Strategy
group Deposit to Morpho Aave Strategy [unallocated WETH in vault]
vault -> morphAaveStrat : WETH
morphAaveStrat -> morpho : WETH
morpho -> aweth : WETH

alt Morpho has more borrows than deposits
morpho -x vdweth : varDebtWETH
note left : repay borrowed WETH from Aave
else Morpho has more deposits than borrows
aweth o-> morpho  : aWETH
note left : deposit WETH to Aave
end
end

end

group Update lock on Frax Convex Strategy [target lock balance < staked balance]

cvxFrxStrat -> frxCvStkLck : stkcvxfrxeth-ng-f-frax
note left : lock Staked Frax Convex LP tokens\n for 7 days by anyone
note right : no locked LP token minted
end


group Update lock on Frax Convex Strategy [target lock balance > expired locked tokens]

frxCvStkLck -> cvxFrxStrat : CRV, CVX & FXS
note left : collects rewards
frxCvStkLck -> cvxFrxStrat : stkcvxfrxeth-ng-f-frax
note left : withdraw locked\nStaked Frax Convex LP tokens
note right : no locked LP token burned
end

' Redeem
group User redeem OETH
vault o-> trust : OETH
note left : 20% performance\nfee from rebase

user -x vault : OETH
note left : burn User's OETH

note over vault : 0.5% fee applied to redeemed assets.\nThis adds to the yield in the next rebase.

' FRAX Strategy
group Withdraw from FRAX Strategy [not enough frxETH in vault]
note over frxStrat
can only redeem frxETH.
depositted WETH is removed as frxETH.
end note
frxStrat -x sfrxETH : sfrxETH
note left : redeem sfrxETH shares
sfrxETH -> user : frxETH
note left : transfer directly to user
' sfrxETH -> vault : frxETH
' note left : transfer to vault
end

' Curve AMO Strategy
group Withdraw from Curve AMO Strategy [not enough WETH in vault]
cvxRewards -x oethCvx : cvxOETHCRV-f
note left : unstake and burn Convex LP tokens
oethCvx -> crvStrat : OETHCRV-f
note left : withdraw Curve pool LP tokens

crvStrat -x oethCrv : OETHCRV-f
note left : burn Curve pool LP tokens
oethCrv -> crvStrat : ETH, OETH
note left : remove liquidity from the Curve pool

crvStrat -x crvStrat : OETH
note left : burn OETH withdrawn from Curve

crvStrat -> weth : ETH
note left : deposit ETH into Wrapped ETH
weth o-> user : WETH
note left : transfer directly to user
' weth o-> vault : WETH
' note left : transfer to vault
end

' Morpho Aave Strategy
group Withdraw from Morpho Aave Strategy [not enough WETH in vault]
alt Morpho has more borrows than deposits
vdweth o-> morpho : varDebtWETH
note left : borrow WETH from Aave
else Morpho has more deposits than borrows
morpho -x aweth : aWETH
note left : withdraw WETH deposit from Aave
end
aweth -> morpho : WETH
morpho -> morphAaveStrat : WETH
' morphAaveStrat -> vault : WETH
morphAaveStrat -> user : WETH
note left : transfer directly to user
end

note over vault : no strategy so comes from vault
vault -> user : stETH
vault -> user : rETH
end

' Curve AMO Strategy - mint and add oTokens
group Strategist mints and adds oTokens to Curve pool [too much ETH in Curve pool]
vault o-> crvStrat : OETH
note left : Vault mints OETH
crvStrat -> oethCrv : OETH
note left : one-sided add liquidity to the Curve pool
oethCrv o-> crvStrat : OETHCRV-f
note left: strategy gets Curve pool LP tokens

crvStrat -> oethCvx : OETHCRV-f
note left : deposit Curve pool LP to Convex
oethCvx o-> cvxRewards : cvxOETHCRV-f
note left : stake Convex LP tokens
end

' Curve AMO Strategy - remove and burn OETH
group Strategist removes and burns oTokens from Curve pool [too much OETH in Curve pool]
cvxRewards -x oethCvx : cvxOETHCRV-f
note left : unstake and burn Convex LP tokens
oethCvx -> crvStrat : OETHCRV-f
note left : withdraw Curve pool LP tokens

crvStrat -x oethCrv : OETHCRV-f
note left : burn Curve pool LP tokens
oethCrv -> crvStrat : OETH
note left : on-sided remove liquidity from the Curve pool

crvStrat -x crvStrat : OETH
note left : burn OETH withdrawn from Curve
end

' Curve AMO Strategy - remove ETH
group Strategist removes ETH from Curve pool [too much ETH in Curve pool]
cvxRewards -x oethCvx : cvxOETHCRV-f
note left : unstake and burn Convex LP tokens
oethCvx -> crvStrat : OETHCRV-f
note left : withdraw Curve pool LP tokens

crvStrat -x oethCrv : OETHCRV-f
note left : burn Curve pool LP tokens
oethCrv -> crvStrat : ETH
note left : on-sided remove liquidity from the Curve pool

crvStrat -> weth : ETH
note left : deposit ETH into Wrapped ETH
weth o-> vault : WETH
note left : transfer to vault
end

' Harvest and swap Convex AMO
group Harvest and swap Convex AMO rewards [can be called by anyone]

cvxRewards -> crvStrat : CVX & CRV
note left : collect Convex rewards
crvStrat -> harv : CVX & CRV
note left : transfer rewards to Harvester

harv -> cvxeth : CVX
note left : exchange CVX for ETH\nmax 2,500 CVX
cvxeth -> weth : ETH
note left : withdraw ETH from Wrapped ETH
weth o-> cvxeth : WETH
cvxeth -> harv : WETH
harv -> drip : 98% WETH
note left : 98% of WETH to Dripper
harv -> anyone : 2% WETH
note left : 2% of WETH\nto Harvest caller

harv -> triCrv : CRV
note left : exchange CRV for WETH\nmax 4,000 CRV
triCrv -> weth : ETH
note left : withdraw ETH from Wrapped ETH
weth o-> triCrv : WETH
triCrv -> harv : WETH
harv -> drip : 98% WETH
note left : 98% of WETH to Dripper
harv -> anyone : 2% WETH
note left : 2% of WETH\nto Harvest caller
end

' Harvest and swap Balancer
group Harvest and swap Balancer rewards [can be called by anyone]

balMetaPool -> balMetaStrat : BAL
note left : collect Balancer rewards
auraRewards  -> balMetaStrat : AURA
note left : collect Aura rewards
balMetaStrat -> harv : BAL & AURA
note left : transfer rewards to Harvester
harv -> balVault : BAL
note left : swap BAL for WETH\nmax 1,000 BAL
balVault -> harv : WETH
harv -> drip : 98% WETH
note left : 98% of WETH to Dripper
harv -> anyone : 2% WETH
note left : 2% of WETH\nto Harvest caller
harv -> balVault : AURA
note left : swap AURA for WETH\nmax 4,000 BAL
balVault -> harv : WETH
harv -> drip : 98% WETH
note left : 98% of WETH to Dripper
harv -> anyone : 2% WETH
note left : 2% of WETH\nto Harvest caller

end

' Harvest and Swap
group Harvest and swap Frax Convex rewards [can be called by anyone]

frxCvStk -> cvxFrxStrat : CRV, CVX
note left : collects staked rewards
frxCvStkLck -> cvxFrxStrat : CRV, CVX & FXS
note left : collects locked rewards
cvxFrxStrat -> harv : CVX, CRV & FXS
note left : transfer rewards to Harvester

harv -> cvxeth : CVX
note left : exchange CVX for ETH\nmax 2,500 CVX
cvxeth -> weth : ETH
note left : withdraw ETH from Wrapped ETH
weth o-> cvxeth : WETH
cvxeth -> harv : WETH
harv -> drip : 98% WETH
note left : 98% of WETH to Dripper
harv -> anyone : 2% WETH
note left : 2% of WETH\nto Harvest caller

harv -> triCrv : CRV
note left : exchange CRV for WETH\nmax 4,000 CRV
triCrv -> weth : ETH
note left : withdraw ETH from Wrapped ETH
weth o-> triCrv : WETH
triCrv -> harv : WETH
harv -> drip : 98% WETH
note left : 98% of WETH to Dripper
harv -> anyone : 2% WETH
note left : 2% of WETH\nto Harvest caller

' FXS swap
harv -> uniFxs : FXS
note left : swap FXS for WETH\nmax 1,500 FXS
uniFxs -> harv : WETH
harv -> drip : 98% WETH
note left : 98% of WETH to Dripper
harv -> anyone : 2% WETH
note left : 2% of WETH\nto Harvest caller

end

' Collect and Rebase
group Collect and Rebase [can be called by anyone]

drip -> vault : WETH
note left : stream harvested WETH\nto Vault over 14 days

group Rebase [increase in underlying assets]
vault o-> vault : 80% OETH
note left : 80% of rebased\nto OETH holders

vault o-> trust : 20% OETH
note left : 20% of rebase\nto trustee as\nperformance fee
end 
end

group Trustee OETH rewards

group OGV buyback for OGV stakers
trust -> uniRouter : OETH
uniRouter -> uniOeth : 50% OETH
note left : swap 50% OETH for WETH\nusing OETH/WETH V3 pool
uniOeth -> uniOgv : WETH
note left : swap WETH for OGV\nusing OGV/WETH V3 pool
uniOgv -> ogvRewards : OGV
note left : transfer OGV\nto Staking Rewards
end

group CVX buyback and locking for increased Convex rewards
uniRouter -> uniOeth : 50% OETH
note left : swap 50% OETH for WETH\nusing OETH/WETH V3 pool
uniOeth -> uniRouter : WETH
uniRouter -> uniCvx : WETH
note left : swap WETH for CVX\nusing CVX/WETH V3 pool
uniCvx -> buyBack : CVX
buyBack -> icvx : CVX
note left : lock CVX for\ngauge voting power
icvx o-> trust : vlCVX
note over trust : Trustee delegates\nvoting power
end

end

' Swap vault collateral assets
group Trustee swaps collateral assets [WETH for rETH]
vault -> swapper : WETH
note left : swap WETH for rETH
swapper -> 1r : WETH
1r -> vault : rETH
end

@enduml
