@startuml

title "Origin USD Contract Dependencies"

object "VaultValueChecker" as checker <<Origin>> #DeepSkyBlue {
}

object "wOUSD" as wousd <<Origin>><<Proxy>> #DeepSkyBlue {
    asset: OUSD
    symbol: wOUSD
    name: Wrapped OUSD
}

object "OUSD" as ousd <<Origin>><<Proxy>> #DeepSkyBlue {
    symbol: OUSD
    name: Origin Dollar
}

object "Vault" as vault <<Origin>><<Proxy>> #DeepSkyBlue {
    assets: USDS, USDC, USDT  
}

object "Harvester" as harv <<Origin>><<Proxy>> #DeepSkyBlue {
    rewards: CRV
}

' Strategies
' object "ConvexStrategy" as cvxStrat <<Origin>><<Proxy>> #DeepSkyBlue {
'     asset: DAI, USDC, USDT
'     Curve pool: 3Pool (3CRV)
'     Convex pool: DAI+USDC+USDT
'     rewards: CRV, CVX
' }
object "Morpho Steakhouse USDC\nStrategy" as steakUSDC <<Origin>><<Proxy>> #DeepSkyBlue {
    asset: USDC
    Morpho vault: steakUSDC
    rewards: MORPHO
}
object "Morpho Gauntlet Prime USDC\nStrategy" as gtUSDC <<Origin>><<Proxy>> #DeepSkyBlue {
    asset: USDC
    Morpho vault: gtUSDC
    rewards: MORPHO
}
object "Curve USDC AMO\nStrategy" as curveAmoStrat <<Origin>><<Proxy>> #DeepSkyBlue {
    asset: USDC
    Curve pool: OUSD/USDC
    rewards: CRV
}

' Oracle
object "OracleRouter" as oracle <<Origin>> #DeepSkyBlue {
pairs:
    USDC/USD
}

checker ..> ousd
checker ..> vault

vault <.. harv 

wousd ..> ousd
ousd <.> vault
vault ..> oracle

' Strategies
' vault <...> aaveStrat
' vault <...> amoStrat
vault <...> steakUSDC
vault <...> gtUSDC
vault <...> curveAmoStrat

' harv <..> amoStrat
harv <...> steakUSDC
harv <...> gtUSDC
harv <...> curveAmoStrat

@enduml