@startuml

title "Origin USD Contract Dependencies"

object "Dripper" as drip <<Origin>><<Proxy>> #DeepSkyBlue {
    asset: USDT
}

object "VaultValueChecker" as checker <<Origin>> #DeepSkyBlue {
}

object "WOUSD" as wousd <<Origin>><<Proxy>> #DeepSkyBlue {
    asset: OUSD
    symbol: WOUSD
    name: Wrapped OUSD
}

object "Flipper" as flipper <<Origin>> #DeepSkyBlue {
    assets: DAI, USDC, USDT
}

object "OUSD" as ousd <<Origin>><<Proxy>> #DeepSkyBlue {
    symbol: OUSD
    name: Origin Dollar
}

object "Vault" as vault <<Origin>><<Proxy>> #DeepSkyBlue {
    assets: DAI, USDC, USDT  
}

object "Harvester" as harv <<Origin>><<Proxy>> #DeepSkyBlue {
    rewards: CRV, CVX
}

object "Buyback" as buy <<Origin>><<Proxy>> #DeepSkyBlue {
swap OUSD for OGV
}

' Strategies
object "AaveStrategy" as aaveStrat <<Origin>><<Proxy>> #DeepSkyBlue {
    asset: DAI, USDC, USDT
    Aave tokens: aDAI, aUSDC, aUSDT
    ' rewards: AAVE
}
' object "CompoundStrategy" as compStrat <<Origin>><<Proxy>> #DeepSkyBlue {
'     asset: DAI, USDC, USDT
'     compound tokens: cDAI, cUSDC, cUSDT
    ' rewards: COMP
' }
' object "ConvexStrategy" as cvxStrat <<Origin>><<Proxy>> #DeepSkyBlue {
'     asset: DAI, USDC, USDT
'     Curve pool: 3Pool (3CRV)
'     Convex pool: DAI+USDC+USDT
'     rewards: CRV, CVX
' }
object "ConvexAMOStrategy" as amoStrat <<Origin>><<Proxy>> #DeepSkyBlue {
    asset: DAI, USDC, USDT
    Curve Metapool: OUSD3CRV-f
    Convex pool: cvxOUSD3CRV-f
    rewards: CRV, CVX
}
' object "ConvexLUSDMetaStrategy" as cxvLusdStrat <<Origin>><<Proxy>> #DeepSkyBlue {
'     asset: DAI, USDC, USDT
'     Curve Metapool: LUSD3CRV-f
'     Convex pool: cvxLUSD3CRV-f
'     rewards: CRV, CVX
' }
' object "MorphoCompoundStrategy" as morphCompStrat <<Origin>><<Proxy>> #DeepSkyBlue {
'     asset: DAI, USDC, USDT
'     Compound tokens: cDAI, cUSDC, cUSDT
    ' rewards: COMP
' }
object "MorphoAaveStrategy" as morphAaveStrat <<Origin>><<Proxy>> #DeepSkyBlue {
    asset: DAI, USDC, USDT
    Aave tokens: aDAI, aUSDC, aUSDT
    ' rewards: AAVE
}

object "FluxStrategy" as fluxStrat <<Origin>><<Proxy>> #DeepSkyBlue {
    asset: DAI, USDC, USDT
    Flux tokens: fDAI, fUSDC, fUSDT
}

object "MakerDsrStrategy" as dsrStrat <<Origin>><<Proxy>> #DeepSkyBlue {
    asset: DAI
    vault: sDAI
}

' Oracle
object "OracleRouter" as oracle <<Origin>> #DeepSkyBlue {
pairs:
    USDT/USD
    USDC/USD
    DAI/USD
    CRV/USD
    CVX/USD 
}

vault <. drip

checker ..> ousd
checker ..> vault

flipper ..> ousd

vault <.. harv 

wousd ..> ousd
ousd <.> vault
vault ..> oracle

buy .> ousd

' Strategies
vault <...> aaveStrat
' vault <...> compStrat
' vault <...> cvxStrat
vault <...> amoStrat
' vault <...> cxvLusdStrat
' vault <...> morphCompStrat
vault <...> morphAaveStrat
vault <...> fluxStrat
vault <...> dsrStrat

drip <.. harv
' harv <..> cvxStrat
harv <..> amoStrat
' harv <..> cxvLusdStrat


@enduml