runtime: nodejs
env: flex
instance_class: B2
manual_scaling:
  instances: 3
service: ousd-prod
handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
readiness_check:
  app_start_timeout_sec: 600
  