minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - "origin-morpho-utils"

ignoredBuiltDependencies:
  - "@arbitrum/nitro-contracts"
  - core-js-pure
  - es5-ext
  - secp256k1
  - utf-8-validate
  - web3
  - web3-bzz
  - web3-shh

onlyBuiltDependencies:
  - "@trufflesuite/bigint-buffer"
  - bigint-buffer
  - bufferutil
  - keccak

packageExtensions:
  "@lodestar/spec-test-util@*":
    peerDependenciesMeta:
      vitest:
        optional: true
  origin-morpho-utils:
    peerDependenciesMeta:
      vitest:
        optional: true

allowBuilds:
  '@trufflesuite/bigint-buffer': true
  bufferutil: true
  core-js-pure: true
  es5-ext: true
  keccak: true
  secp256k1: true
  utf-8-validate: true
  web3: true
  web3-bzz: true
  web3-shh: true
