name: Danger CI

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 20x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "yarn"
      - run: yarn install  --frozen-lockfile
      - run: yarn danger ci
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
