name: Danger CI

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Force Git deps to use HTTPS instead of SSH
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10
          run_install: false
          
      - name: Use Node.js 20x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      - run: pnpm danger ci
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
