name: DApp Tests
on: [push, pull_request]

concurrency:
  cancel-in-progress: true
  group: ${{ github.ref_name }}

jobs:
  dapp-lint:
    name: "Linter"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "14.x"

    - run: yarn config set cacheFolder /runner/_work/.yarn-cache

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: 1-${{ runner.os }}-yarn-${{ hashFiles('dapp/yarn.lock') }}-dapp
        restore-keys: |
          1-${{ runner.os }}-yarn-dapp

    - run: yarn install
      working-directory: ./dapp

    - run: yarn prettier:check
      working-directory: ./dapp
